#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# only run the commit message check if the commit is against the main branch
if [[ $(git rev-parse --abbrev-ref HEAD) = main ]];
then npx --no -- commitlint --edit "${1}";
fi
